#!/bin/sh
DEVEL_DIR=~/Devel
QT5_DIR=~/Qt/5.15.1/gcc_64/lib/cmake/Qt5
FIRSTTASK_SOURCE_DIR=$DEVEL_DIR/FirstTaskApp
FIRSTTASK_SUPERBUILD_BIN_DIR_DBG_X64=$DEVEL_DIR/fD
FIRSTTASK_SUPERBUILD_BIN_DIR_REL_X64=$DEVEL_DIR/fR
SLICER_BIN_DIR_DBG_X64=$FIRSTTASK_SUPERBUILD_BIN_DIR_DBG_X64/Slicer-build
SLICER_BIN_DIR_REL_X64=$FIRSTTASK_SUPERBUILD_BIN_DIR_REL_X64/Slicer-build
